/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void btn_start_onClick(GButton source, GEvent event) { //_CODE_:btn_start:879071:
  //println("btn_start - GButton >> GEvent." + event + " @ " + millis());
  if(!system_detected){
    msgBx_msg = "No puede comenzar la lectura sin conectar previamente el sistema.";
    msgBx_title = "Error";
    MsgBox(msgBx_msg, msgBx_title); 
  }
  else if(!at_least_1_read){
    msgBx_msg = "\nCélula en proceso de tara.\n\nEspere a la indicación para comenzar el ensayo...     ";
    msgBx_title = "Sistema en preparación";
    MsgBox(msgBx_msg, msgBx_title);
  }
  else{
    // Manual exit
    if(test_running){
      outputFile.close();
      PImage capture_carga_deformacion = get(480,0,480,430);
      capture_carga_deformacion.save(sketchPath("")+"AXIALATOR_carga_deformacion.jpg");      
      PImage capture_carga_tiempo = get(0,430,480,430);
      capture_carga_tiempo.save(sketchPath("")+"AXIALATOR_carga_tiempo.jpg");      
      PImage capture_deformacion_tiempo = get(480,430,480,430);
      capture_deformacion_tiempo.save(sketchPath("")+"AXIALATOR_deformacion_tiempo.jpg");
      msgBx_msg = "\nLos datos han sido almacenados en el fichero values.txt  \n\n"+
                  "Seleccione dicho fichero desde Excel > Datos > Obtener y transformar datos > Desde el texto/CSV  \n\n"+
                  "Nota: seleccione Espacio como elemento separador\n\n"+
                  "Se ha guardado una captura de las gráficas obtenidas en el ensayo.\n\n\n\n"+
                  "Gracias por usar Axialator.";
      msgBx_title = "Ensayo finalizado";
      MsgBox(msgBx_msg, msgBx_title);
      exit();
    }
    else{
      str_1st_msg = "Registrando datos...";
      str_2nd_msg = "Pulse Finalizar cuando haya acabado.";  
      timeOffset = time;
    }
    test_running = !test_running;
  }
} //_CODE_:btn_start:879071:

public void btn_help_onClick(GButton source, GEvent event) { //_CODE_:btn_help:909491:
  //println("btn_help - GButton >> GEvent." + event + " @ " + millis());
  msgBx_msg = "Information.";
  msgBx_title = "Title";
  MsgBox(msgBx_msg, msgBx_title);
} //_CODE_:btn_help:909491:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("");
  lbl_copyright = new GLabel(this, 10, 380, 460, 20);
  lbl_copyright.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lbl_copyright.setText("(C) Ramón Arteaga & Javier Van Baumberghen - 2017");
  lbl_copyright.setOpaque(false);
  btn_start = new GButton(this, 190, 260, 110, 50);
  btn_start.setText("Comenzar");
  btn_start.setTextBold();
  btn_start.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  btn_start.addEventHandler(this, "btn_start_onClick");
  lbl_title = new GLabel(this, 10, 40, 460, 40);
  lbl_title.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lbl_title.setText("Software Title");
  lbl_title.setOpaque(false);
  lbl_1st_msg = new GLabel(this, 10, 120, 460, 30);
  lbl_1st_msg.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lbl_1st_msg.setText("First message");
  lbl_1st_msg.setOpaque(false);
  lbl_2nd_msg = new GLabel(this, 10, 160, 460, 66);
  lbl_2nd_msg.setTextAlign(GAlign.CENTER, GAlign.TOP);
  lbl_2nd_msg.setText("Second message");
  lbl_2nd_msg.setOpaque(false);
  lbl_status = new GLabel(this, 190, 230, 170, 20);
  lbl_status.setText("System Status");
  lbl_status.setOpaque(false);
  lbl_credit = new GLabel(this, 10, 400, 460, 20);
  lbl_credit.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lbl_credit.setText("Departamento de Siderurgia - ETSII UPM");
  lbl_credit.setOpaque(false);
  btn_help = new GButton(this, 220, 340, 50, 20);
  btn_help.setText("Ayuda");
  btn_help.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  btn_help.addEventHandler(this, "btn_help_onClick");
}

// Variable declarations 
// autogenerated do not edit
GLabel lbl_copyright; 
GButton btn_start; 
GLabel lbl_title; 
GLabel lbl_1st_msg; 
GLabel lbl_2nd_msg; 
GLabel lbl_status; 
GLabel lbl_credit; 
GButton btn_help; 